### PR TITLE
Improve task reference validation

### PR DESCRIPTION
**Pull request by Krakenied**
Closes https://github.com/LMBishop/Quests/issues/619

### CODE REVIEW

**Comment by Krakenied** [comment]
Temporarily changed to a draft

**Comment by Krakenied** [comment]
Example:
```yml
tasks:
  BLOCKPLACIIIIIING:
    type: blockplace
    amount: 100000
    block: COBBLESTONE
    reverse-if-broken: true
    allow-negative-progress: false
  STONEPLACING:
    type: blockplace
    amount: 100000
    block: STONE
    reverse-if-broken: true
    allow-negative-progress: false
progress-placeholders:
  "*": "{this:id} &8» &#FDCD00{this:progress}&f, stone&8: &#FDCD00{STONEPLACING:progress}&f, &fcobble&8: &#FDCD00{BLOCKPLACIIIIIING:progress}"
```

https://github.com/LMBishop/Quests/assets/46192742/742c9cb2-3bde-46cb-b890-3751c5eab0f4

**Comment by Krakenied** [comment]
Another nice example:
```yml
tasks:
  BLOCKPLACIIIIIING:
    type: blockplace
    amount: 100000
    block: COBBLESTONE
    reverse-if-broken: true
    allow-negative-progress: false
  STONEPLACING:
    type: blockplace
    amount: 100000
    block: STONE
    reverse-if-broken: true
    allow-negative-progress: false

placeholders:
  displayPrefixBLOCKPLACIIIIIING: "&3Cobble placing"
  displayPrefixSTONEPLACING: "&9Stone placing"

progress-placeholders:
  "*": "%quests_quest:example1_p:displayPrefix{this:id}% &8» &#FDCD00{this:progress}&f, stone&8: &#FDCD00{STONEPLACING:progress}&f, &fcobble&8: &#FDCD00{BLOCKPLACIIIIIING:progress}"
```


https://github.com/LMBishop/Quests/assets/46192742/7290c4b1-1ada-4d3f-af43-43ff4717ce1c

**Comment by Krakenied** [comment]
This is supported too (defining progress placeholder by task type):
```yml
tasks:
  BLOCKPLACIIIIIING:
    type: blockplace
    amount: 100000
    block: COBBLESTONE
    reverse-if-broken: true
    allow-negative-progress: false
  STONEPLACING:
    type: blockplace
    amount: 100000
    block: STONE
    reverse-if-broken: true
    allow-negative-progress: false

placeholders:
  displayPrefixBLOCKPLACIIIIIING: "&3Cobble placing"
  displayPrefixSTONEPLACING: "&9Stone placing"

progress-placeholders:
  blockplace: "%quests_quest:example1_p:displayPrefix{this:id}% &8» &#FDCD00{this:progress}"
```

https://github.com/LMBishop/Quests/assets/46192742/35f85dad-b74b-4bc5-9f7b-a966562117f4

**Comment by Krakenied** [comment]
https://github.com/LMBishop/Quests/pull/617 and https://github.com/LMBishop/Quests/pull/621 should be merged before this to avoid most of the possible conflicts lol

**Comment by LMBishop** [comment]
Could you rebase onto `master`, seems like there are a couple of conflicts with your other PRs 😛

**Comment by Krakenied** [comment]
sure

**Comment by Krakenied** [comment]
done @LMBishop

**Review by LMBishop — APPROVED** [review]

**Comment by LMBishop** [comment]
> done @LMBishop

Thanks!

**Pull request merged**
