### PR TITLE
Add item breaking, mending and damaging; curing and resurrecting task types

### PR DESCRIPTION
**Pull request by Krakenied**
Closes https://github.com/LMBishop/Quests/issues/545 (only curing is possible to implement)
Closes https://github.com/LMBishop/Quests/issues/489 (added curing task type)
Closes https://github.com/LMBishop/Quests/issues/645 (fixed autosave)
Closes https://github.com/LMBishop/Quests/issues/672 (made the error a bit cleaner)
Closes https://github.com/LMBishop/Quests/issues/670 (already fixed)
Closes https://github.com/LMBishop/Quests/issues/659 (made the error a bit cleaner)
Closes https://github.com/LMBishop/Quests/issues/629 (optimized debugging)
Closes https://github.com/LMBishop/Quests/issues/667 (added cancelstring and expirystring)

### CODE REVIEW

**Comment by Krakenied** [comment]
rebased onto https://github.com/LMBishop/Quests/pull/642

**Comment by Krakenied** [comment]
rebased back onto master

**Comment by Krakenied** [comment]
Ill mark it as ready for review and continue work on another PR

**Comment by Krakenied** [comment]
@LMBishop

**Comment by Krakenied** [comment]
Merged https://github.com/LMBishop/Quests/pull/671

**Comment by Krakenied** [comment]
No more changes planned to this PR

**Review by LMBishop — APPROVED** [review]

**Pull request merged**
