### PR TITLE
Add CustomFishing compatibility

### PR DESCRIPTION
**Pull request by Xiao-MoMi**

### CODE REVIEW

**Comment by NoltoxGit** [comment]
Fixed this issue: https://github.com/LMBishop/Quests/issues/574.

**Comment by Krakenied** [comment]
These task types can be merged into one

**Comment by Xiao-MoMi** [comment]
Builded the latest jar and now waiting for the test result from @NoltoxGit

**Comment by NoltoxGit** [comment]
> Builded the latest jar and now waiting for the test result from @NoltoxGit

Yeah, I just tested the new .jar and it looks all good to me, apart the fact that it would be that @Krakenied you try to add the `world:` option otherwise it's perfect!

**Comment by Krakenied** [comment]
> > Builded the latest jar and now waiting for the test result from @NoltoxGit
> 
> Yeah, I just tested the new .jar and it looks all good to me, apart the fact that it would be that @Krakenied you try to add the `world:` option otherwise it's perfect!

It's already added

**Comment by NoltoxGit** [comment]
> > > Builded the latest jar and now waiting for the test result from @NoltoxGit
> > 
> > 
> > Yeah, I just tested the new .jar and it looks all good to me, apart the fact that it would be that @Krakenied you try to add the `world:` option otherwise it's perfect!
> 
> It's been already added

Hmm, so it doesn't work :')

**Comment by Krakenied** [comment]
> > > > Builded the latest jar and now waiting for the test result from @NoltoxGit
> > > 
> > > 
> > > Yeah, I just tested the new .jar and it looks all good to me, apart the fact that it would be that @Krakenied you try to add the `world:` option otherwise it's perfect!
> > 
> > 
> > It's been already added
> 
> Hmm, so it doesn't work :')

It uses task constraints so probably the option is `worlds` instead of `world`

**Comment by NoltoxGit** [comment]
> > > > > Builded the latest jar and now waiting for the test result from @NoltoxGit
> > > > 
> > > > 
> > > > Yeah, I just tested the new .jar and it looks all good to me, apart the fact that it would be that @Krakenied you try to add the `world:` option otherwise it's perfect!
> > > 
> > > 
> > > It's been already added
> > 
> > 
> > Hmm, so it doesn't work :')
> 
> It uses task constraints so probably the option is `worlds` instead of `world`

Ohh yeah... i'm dumb asf :c

**Review by LMBishop — APPROVED** [review]

**Pull request merged**
