### PR TITLE
Fix not deleted bossbar

### PR DESCRIPTION
**Pull request by Elikill58**
If you have the bossbar when the server goes down, you will keep the bossbar forever as it's saved in world.

With this PR, it's fixed.

(Thanks Hamta for reporting this issue)

### CODE REVIEW

**Comment by Krakenied** [comment]
That's exactly the reason I said you shouldn't be using keyed bossbars for such a feature...

**Comment by Elikill58** [comment]
> That's exactly the reason I said you shouldn't be using keyed bossbars for such a feature... It's also bad in terms of performance.

Where did you said that? Also, what could the other way? Without key but with bukkit bossbar they will be saved too. Else, with Adventure they will not but it's a paper-only feature

**Comment by Krakenied** [comment]
Without key the bossbars shouldnt be saved

**Comment by Elikill58** [comment]
> Without key the bossbars shouldnt be saved

Oh yes, I just checked javadoc and you're right.
I used key for simplicity to get the bossbar, but as you said we can use without key but we should save all bossbar by ourself

**Review by LMBishop — APPROVED** [review]

**Comment by LMBishop** [comment]
Could you rebase your branch to resolve the merge conflict? I would do it for you but I do not want to modify the master branch in your repository

**Comment by Elikill58** [comment]
I just discord commit and make it again for cleaner commit :) But why you don't like tabs?

**Comment by LMBishop** [comment]
> I just discord commit and make it again for cleaner commit :) But why you don't like tabs?

Thanks, the rest of the project uses spaces so I do not want to end up with mixed indentation

**Comment by Krakenied** [comment]
> I just discord commit and make it again for cleaner commit :) But why you don't like tabs?
Just for consistency. A tab could be a different number of columns depending on your environment, but a space is always one column.

**Pull request merged**
