### PR TITLE
Improve boss bars performance, add hex support to action bars, add task type for block brushing (and more)

### PR DESCRIPTION
**Pull request by Krakenied**
Closes https://github.com/LMBishop/Quests/issues/517
Closes https://github.com/LMBishop/Quests/issues/544
An example task to get 30 light blue stained glass panes by brushing sus sand and gravel
```
  bid:
    type: "blockitemdropping"
    amount: 30
    blocks:
    - SUSPICIOUS_SAND
    - SUSPICIOUS_GRAVEL
    item: LIGHT_BLUE_STAINED_GLASS_PANE
```
Closes https://github.com/LMBishop/Quests/issues/548
Closes https://github.com/LMBishop/Quests/issues/519
Closes https://github.com/LMBishop/Quests/issues/247
Closes https://github.com/LMBishop/Quests/issues/110

### CODE REVIEW

**Comment by Krakenied** [comment]
needs testing

**Comment by WarnDa** [comment]
Thanks a lot for this PR ! 
I can't test is except on test server (still not running the plugin on prod)

Is this also planned that you change how the bossbar work with multiple objective ? (here is the message I wrote) 
image

**Comment by Krakenied** [comment]
It's still a draft so I can try implementing such a feature

**Comment by Krakenied** [comment]
rebased

**Comment by Krakenied** [comment]
from my testing it seems to be working, example:
```
tasks:
  mining:
    type: "blockbreak"
    amount: 30
progress-placeholders:
  mining: "&8- &f{mining:progress}&7/30 broken"

**Comment by WarnDa** [comment]
> from my testing it seems to be working, example:
> 
> ```yaml
> tasks:
>   building:
>     type: "blockplace"
>     amount: 30
>   mining:
>     type: "blockbreak"
>     amount: 30
> progress-placeholders:
>   mining: "&8- &f{mining:progress}&7/30 broken"
>   building: "&8- &f{building:progress}&7/30 placed"
> placeholders:
>   progress: " &8- &f{mining:progress}&7/30 broken" # option for any task not defined in the section above
> ```

Wow it's perfect for me !
Possible to get a .jar ? So I can continue configuring my quests with this syntaxe (not to have to replace all the files after the update lol)

**Comment by Krakenied** [comment]
@WarnDa just added also an option to specify one title format for all quest's tasks
The order plugin checks for it is:
1. `progress-placeholders.specific_task_id`
2. `progress-placeholders.*` <--- and there you should use it as in the example below
3. `placeholders.progress` (just for a fallback)

```yml
tasks:
  building:
    type: "blockplace"
    amount: 30
  mining:
    type: "blockbreak"
    amount: 30
  shearing:
    type: "shearing"
    amount: 30
progress-placeholders:
  mining: "&8- &f{mining:progress}&7/30 broken" # it will be used only for mining
  # btw u are able to just use {this:progress} or {anything_else:progress}
  # because the way it works doesn't depend on the left part of the placeholder
  # (kinda *unfortunately* but if it works then it works lol)
  "*": "&8PROGRESS IS NOW {this:progress}" # and it will be shown for
                            # building and shearing (its like 1st fallback)
placeholders:
  progress: " &8- &f{mining:progress}&7/30 broken" # will be used only in GUI cuz
                               # its like 2nd fallback but already 1st one is set (the "*" one)

**Comment by WarnDa** [comment]
Thanks I'm trying this now, but did I miss a config settings to enable the new bossbar ?

It displays the "placeholders" instead of the cobblestone "progress-placeholders:" when I mine dirt or stone

```yaml
tasks:
  cobblestone:
    type: "blockbreakcertain"
    amount: 130
    block: COBBLESTONE
  stone:
    type: "blockbreakcertain"
    amount: 220
    block: STONE
  dirt:
    type: "blockbreakcertain"
    amount: 225
    block: DIRT

progress-placeholders:
  cobblestone: "&7Cobble &f{cobblestone:progress} &f/ &f130"
  stone: "&7Stone &f{cobblestone:progress}&f/&f220"
  "*": "&8PROGRESS IS NOW {this:progress}"

placeholders:
  progress: "&7FALLBACK Stone &f {cobblestone:progress}"
  ```
  
image

**Comment by Krakenied** [comment]
Needed that option to do not show boss bar in quests with a _hidden secret_ objective

**Comment by Krakenied** [comment]
> Once this is ready I will start preparing the next release of Quests (v3.15)
> 
> > Is this also planned that you change how the bossbar work with multiple objective ?
> 
> @WarnDa re: I have a rough idea on implementing a way for task types to generate/specify their own objective strings to allow this to happen and reduce the amount of configuration required

I'm gonna fix these for 3.15 too
- [ ] https://github.com/LMBishop/Quests/issues/548
- [ ] https://github.com/LMBishop/Quests/issues/544

**Comment by Krakenied** [comment]
rebased

**Comment by WarnDa** [comment]
Hello,
Does the commit also support Kelp ?
As I only see :
```        if (type == Material.BAMBOO || type == Material.CACTUS || type == Material.SUGAR_CANE) {
            performAgeCheck = false;```

**Comment by LMBishop** [comment]
Could you squash some of your commits as I use the messages in the change log

**Comment by Krakenied** [comment]
Yeah

**Comment by Krakenied** [comment]
Done, added new options too
https://github.com/Krakenied/Quests/blame/15011f6802dec435ad33160090eed425218024d1/bukkit/src/main/resources/resources/bukkit/config.yml#L45-L48

**Comment by WarnDa** [comment]
> Done, added new options too ([15011f6](https://github.com/LMBishop/Quests/commit/15011f6802dec435ad33160090eed425218024d1))

In QuestCreator I asked the dev to add an option to set the bossbar color depending on the quest progress, for example :
```yaml
# Display bossbars from quests in quests in different colors, relative to the current progression ?
quest_progress_notify_bossbars_dynamic_enabled: true
quest_progress_notify_bossbars_dynamic_colors:
  - min: 0
    max: 0.33
    color: WHITE
  - min: 0.33
    max: 0.66
    color: WHITE
  - min: 0.66
    max: 1
    color: WHITE
    ```
    If you find the idea cool, feel free to add it :)

**Review by LMBishop — APPROVED** [review]

**Pull request merged**
