### PR TITLE
A lot of changes and improvements. Again.

### PR DESCRIPTION
**Pull request by Krakenied**
Closes https://github.com/LMBishop/Quests/issues/495
Closes https://github.com/LMBishop/Quests/issues/427
Closes https://github.com/LMBishop/Quests/issues/424
Closes https://github.com/LMBishop/Quests/issues/282

### CODE REVIEW

**Review by LMBishop — APPROVED** [review]

**Comment by Krakenied** [comment]
Testing these changes now

**Comment by Krakenied** [comment]
More changes to test now ^_^

**Comment by Krakenied** [comment]
I think it's high time a new Quests update was released cuz it contains many new features and fixes and probably can now be considered as stable. Need one more week to ensure that's stable.

**Comment by LMBishop** [comment]
🫡 Sorry I've been a bit inactive recently, but I'll make sure to merge this today or tomorrow and start looking to preparing a release soon

**Pull request merged**
