### PR TITLE
Fix not deleted bossbar when stop the server again

### PR DESCRIPTION
**Pull request by Elikill58**
It's nice you made changes for async, but with this you re-create a new bug with bossbar that are not disappearing when restarting the sevrer.

Actually, bossbar created and not deleted could not be removed by owner as they are not showed in `/bossbar remove` command.

### CODE REVIEW

**Comment by Krakenied** [comment]
Make sure your server fork and your plugins dont break boss bar behavior, im unable to reproduce the issue

**Comment by Krakenied** [comment]
(unused boss bars are automatically collected by GC)

**Comment by Krakenied** [comment]
(so there is a memory leak on your server which is definitely not a sensible reason to put more unnecessary code to the plugin lol)

**Comment by Krakenied** [comment]
tbh it's also possible that there are old boss bars present on your server which were created using the keyed method

**Comment by Krakenied** [comment]
also, your fix will most likely cause CME because keyed boss bars are stored server side in a HashMap

**Comment by Elikill58** [comment]
And not keyed bossbar are not saved ? Also, with this fix, the server that report me this bug no longer have issue.
They are using purpur

**Comment by Krakenied** [comment]
> And not keyed bossbar are not saved ? Also, with this fix, the server that report me this bug no longer have issue. They are using purpur

Simple boss bars aren't saved at all:
image
image

Keyed boss bars are:
image
image
image

As you can see, there is no logic to store the simple boss bars (they are basically collected by garbage collector), whereas the keyed one are stored in a hash map and are even saved in the world files, making it necessary to remove them manually.

**Comment by Elikill58** [comment]
Oh ok. And did you check if the /save-all command for example save them manually ? Like if there is another system that save them ?

**Comment by Krakenied** [comment]
image
As you can see, CustomBossEvents is empty after running the /save-all command


https://github.com/LMBishop/Quests/assets/46192742/ba5533c0-8ba8-4a0b-b9b9-e5bc30ee914f

**Comment by Elikill58** [comment]
Oh ok, thanks for all of this informations, and sorry for disturbing

**Pull request closed without merging**
