### PR TITLE
improv. fix multiple datas

### PR DESCRIPTION
**Pull request by nivcoo**
This allows you to do this kind of configuration https://pics.edensky.fr/2021-02/06/14-01_mv6I.png

### CODE REVIEW

**Comment by nivcoo** [comment]
I fix also the issue with return false with multiple blocks (Sorry for multiple commit, indent issue :x)

**Comment by nivcoo** [comment]
Could you update on spigot ? I use a fork actually for this fix. Thx

**Comment by LMBishop** [comment]
The release update for this will be published with the other planned 2.13 features / fixes in the [milestone](https://github.com/LMBishop/Quests/milestone/2). Your merged fixes were automatically built [here](https://github.com/LMBishop/Quests/actions) if you need it before the Spigot update is ready

**Comment by nivcoo** [comment]
Yes but i've always the update warning message

**Comment by LMBishop** [comment]
You can add a file called "stfuQuestsUpdate" in the plugin folder, it will prevent the plugin from automatically checking for updates https://github.com/LMBishop/Quests/blob/master/src/main/java/com/leonardobishop/quests/Quests.java#L200. Also the github builds use the latest release version as the version in the plugin.yml

**Pull request merged**
