### PR TITLE
Ignore NOTHING inventory actions in crafting task type

### PR DESCRIPTION
**Pull request by Krakenied**
Fixes https://github.com/LMBishop/Quests/issues/362

### CODE REVIEW

**Comment by amarcais53** [comment]
would it be possible to build the JAR ? i think the owner is pretty AFK

**Comment by Krakenied** [comment]
> would it be possible to build the JAR ? i think the owner is pretty AFK @Krakenied

JAR based on this PR is available in `Actions` TAB

**Comment by amarcais53** [comment]
> > would it be possible to build the JAR ? i think the owner is pretty AFK @Krakenied
> 
> JAR based on this PR is already available in `Actions` TAB

oh thankyou i have checked it and miss readed

**Comment by amarcais53** [comment]
tested theses changes and issue #362 is fixed

**Review by LMBishop — APPROVED** [review]

**Comment by LMBishop** [comment]
Thanks, https://github.com/LMBishop/Quests/commit/f0edeee46353c15c81083708ca52f17fa1d46647
(Rebased onto master)

**Pull request closed without merging**
