### PR TITLE
Remove unnecessary HashMap#containsKey call from hot path

### PR DESCRIPTION
**Pull request by Krakenied**
Related to https://github.com/LMBishop/Quests/issues/629

### CODE REVIEW

**Comment by Krakenied** [comment]
Songoda repo is down xD

**Comment by LMBishop** [comment]
Tempted to enable proxying on my own repo to not have to deal with annoying repositories with a terrible uptime

**Comment by Krakenied** [comment]
Yeah but its `Received status code 525 from server` (SSL handshake failed) this time

**Comment by LMBishop** [comment]
re-ran it and it's passed now

**Review by LMBishop — APPROVED** [review]

**Pull request merged**
