### PR TITLE
Add cancel commands

### PR DESCRIPTION
**Pull request by Krakenied**
Partially closes https://github.com/LMBishop/Quests/issues/558

### CODE REVIEW

**Comment by DonKolia** [comment]
Dont forget add it to Wiki, like this, is only a idea:
image

**Comment by Krakenied** [comment]
as_console: and as_op: will be implemented soon in another pr

**Comment by DonKolia** [comment]
Check Conditional Events plugin, is open-source, U have it.

**Comment by DonKolia** [comment]
https://github.com/Ajneb97/ConditionalEvents

**Comment by DonKolia** [comment]
Or BetonQuest

**Review by LMBishop — APPROVED** [review]

**Pull request merged**
