### PR TITLE
Some optimizations, fixes and a new task type

### PR DESCRIPTION
**Pull request by Krakenied**

### CODE REVIEW

**Comment by Krakenied** [comment]
FINALLY

**Comment by Krakenied** [comment]
Due to the debug logging optimization it's not minor anymore :kekw:

**Comment by LMBishop** [comment]
Awesome stuff. Could you rebase the branch so the merge commit [d1d4524](https://github.com/LMBishop/Quests/pull/450/commits/d1d45249f4a010772898301938527d86ee41642e) is removed?

**Comment by Krakenied** [comment]
Done

**Review by LMBishop — APPROVED** [review]

**Pull request merged**
